### ISSUE TITLE
GPIO access via sysfs likely to be dropped

### ISSUE THREAD

**Issue by 6by9** [WiringPi/WiringPi#186]
As a heads up.

The Linux kernel since 6.2 is warning if GPIO drivers try and force specific GPIO base numbers for use by sysfs. https://github.com/raspberrypi/linux/commit/502df79b860563d79143be7a1453c2b3224cd836

Due to this, Pi kernels from 6.5 onwards will not be forcing the base GPIO number for the bcm2835 GPIOs to 0
https://github.com/raspberrypi/linux/pull/5638

This has been noted to cause a failure with WiringPi.
https://github.com/raspberrypi/linux/issues/5668

sysfs for GPIO access has been deprecated in the kernel for 8 years, and was nominally scheduled for removal in 2020 (no one has done that quite yet) https://github.com/raspberrypi/linux/commit/fe95046e960b4b76e73dc1486955d93f47276134

A shift to libgpio really should be on the cards for WiringPi.

**Comment by Gadgetoid** [comment]
> A shift to libgpio really should be on the cards for WiringPi.

Thanks for the heads up.

I don't generally know what the state of ongoing maintenance here is, it may be that there's nobody willing to bring WiringPi kicking and screaming into the future- and that's okay. Gordon H EOL'd it and we've had it on life support since.

Broadly, authors of GPIO-based projects should be looking to make the switch to libgpiod, though I do appreciate that the original premise of WiringPi was... well... familiarity.

Some good alternatives that aren't libgpiod include lgpio - https://github.com/joan2937/lg - which is a kitchen-sink-included C library for GPIO, PWM, Serial, i2c and SPI aiui, that's based around standard interfaces and (famous last words) Future Proof. I guess *theoretically* WiringPi could follow suit, but with nobody with the knowledge and inclination to do the leg work, it's more likely just to fade into obscurity.

On the Python side of things I'm migrating to libgpiod (or gpiod) which I am working with Bart (the libgpiod maintainer) to suit my (and hopefully other folks) needs. Any fancy abstractions, device mapping, or otherwise should live as a layer above that - like gpiozero does.

Why wont this library die 😆

**Comment by df8oe** [comment]
It would be a pity if wiringpi would die. Most examples which use GPIOs are working with wiringpi base. I by myself uses it for an interrupt driven counter. A very small application which runs in background and uses nearly no CPU ressources. It awakes when a signal edge occurs (two GPIOs are watched) via interrupt and then only increases a counter in a file. Therefore I use two interrupts (two pins are monitored) and two interrupts. It is very simple to implement with wiringpi - yesterday I do not found an example or solution with any other library. Much of the flexibility and/or power of RPI would vanish. It would be degrated to a simple mini PC without the power of a programmable microcontroller...

**Comment by Gadgetoid** [comment]
This is the sort of use-case that the kernel GPIO drivers are - afaik - ideal for. Should - in  theory - run rings around WiringPi and be portable to boot.

Unfortunately libgpiod has been in flux for a long time and that’s caused a lack of uptake which has made it even harder for people to find a good example or starting point for their use case. Continuing to use old proprietary libraries like WiringPi doesn’t get us anywhere toward fixing that.

WiringPi doesn’t really do anything novel anymore. It offers a bunch of additional device drivers (arguably these are supposed to be kernel modules), some features like mapping IO expanders to GPIO (again maybe Linux does this now anyway?) and a specific way of working that’s conducive to people familiar with Arduino/Wiring.

IMHO it’s a better use of people’s time to migrate wiring holdouts over to libgpiod and start producing a corpus of standards-based GPIO examples.

That said, I steer this project with gentle nudges and hands off, I’m not going to throw my weight around in service of my opinions. If anyone wants to step up and bring WiringPi up to date, be my guest! But I am far, far too busy elsewhere to do it myself.

**Comment by 6by9** [comment]
Routing direct interrupt handling to userspace is generally a bad idea - what happens if your application quits and is unable to service an interrupt?

libgpio supports edge events (https://libgpiod.readthedocs.io/en/latest/group__edge__event.html) which are the safer bet, or as gadgetoid says actually keep this in the kernel

**Comment by df8oe** [comment]
This "bad idea" ist the only way I can use (except I use additionally hardware, what wiringpi excellent solves. Sometimes it lasts days if a pulse occurs. I cannot waste CPU time for bitbanging all the time. So RPI losts some adavntages with the dying of sysfs kernel support. I think this behaviour is ist what pushes users to Microsoft: they never would act that way. It is a loss of possibilities and the death of many (for years running) projects.

**Comment by 6by9** [comment]
This is not my library. The original author it deprecated 4 years ago due to users "bleating on" - https://web.archive.org/web/20220405225008/http://wiringpi.com/wiringpi-deprecated/

A quick read of the code actually shows that their "interrupt handling" is really only using the edge detection off [/sys/class/gpio/gpioN/edge](https://github.com/WiringPi/WiringPi/blob/master/gpio/gpio.c#L625), which is polling rather than an interrupt. Why abuse the terminology?!

Their "interrupt" is a thread created in [wiringPiISR](https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPi.c#L2075) that is calling [`poll` on the edge fd](https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPi.c#L1924). (Don't ask me why they need to [spawn `gpio` as an external app](https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPi.c#L2040) to set up some of this stuff)
Functionally that is exactly the same as the edge events of libgpio that I've already linked to. No bitbanging involved whatsoever.

No "loss of advantage", just a need to actually realise that code bit-rots and needs reworking. If there are no maintainers around prepared to rework it, then it stops working.

And I can never think of a company that would:
- push apps into C:\Program Files.
- lock down access to C:\Program Files
- add in C:\Program Files (x86) (also locked down)
- same for system, system32, and root directories.
to name 4 significant changes.

**Comment by df8oe** [comment]
This was not meant bothering you. It was targeted to the kernel supporters who drop sometihing what must not be dropped. It could stay for compatibility resons with "older software". No need to remove it. OK: it will not support newer hardware /different controller architectures. But it worked perfectly up to pi4...

**Comment by 6by9** [comment]
The sysfs interface has stayed for compatibility reasons for 8 years, which is 3 years beyond where it was stated it would be considered for removal. How long do you think is reasonable to keep junk in the kernel?
There's always the option of you stepping up and maintaining the legacy code - that's part of open source.

And for reference, Ubuntu has pulled sysfs access for GPIOs totally since Ubuntu 22.10 (Kinetic) - https://waldorf.waveform.org.uk/2022/the-one-where-dave-breaks-stuff.html
Times change, and libraries need to actually be maintained, or die.

Half the reason for this fork of WiringPi happening was the Pi4 wasn't supported in the original at the point of it being deprecated. And I can say for certain that Pi5 is not going to be supported where this library dips down into poking registers directly. Having Pi5 users as second class citizens is just as confusing.

The kernel in Raspberry Pi OS isn't going to change from 6.1 until the next LTS is confirmed and that has stabilised (likely 6.7 in the Feb or March) , so there's more than 3 months for PRs to appear for WiringPi.

**Comment by seamusdemora** [comment]
I share @df8oe 's perspective wrt WiringPi.  

Wrt @6by9 's comments: 

1. Thank you for the heads up.
2. I don't completely understand the reasoning offered justifying the deprecation of sysfs and the ascendance of libgpio.  But I'll accept that, from the RPi perspective, the justification is offered in good faith.   
3. Wrt the comments re the "original author":  Gordon's comments mustn't be taken literally as he was/is suffering with mental health issues. BTW, I've seen snarkier comments from RPi personnel over less! 
4. Blaming doesn't solve problems, but I do not understand the kernel maintainers rationale for pushing the libgpio solution. IMHO, it is (or has been) a deeply flawed effort from the beginning. 

And so that is the gist of my feelings on this. It seems (to me) that the issue may lie with the kernel's stubborn adoption of libgpio regardless of consequences, and regardless of its "quality".  I wish there were a way to get this across to them.  Is this gpio business the **only thing** that is holding up deprecation of sysfs??

**Comment by 6by9** [comment]
sysfs for GPIO has always sucked with things like no concept of ownership, and having to have a file descriptors per gpio.
Please accept that it is going the way of the dodo, or sign up to linux-gpio mailing list and express your displeasure there. It's a mainline decision, so complaining about it here or about the Pi kernel has very little effect.

WiringPi is fixable to adapt to libgpio, but it needs someone (anyone - it's open source) to invest the time to do it.

**Comment by Gadgetoid** [comment]
> I wish there were a way to get this across to them. Is this gpio business the **only thing** that is holding up deprecation of sysfs??

[sysfs has been obsolete since 2015 and removed since 2020](https://lore.kernel.org/all/1445502750-22672-7-git-send-email-linus.walleij@linaro.org/). If we wanted to have a say, we should have been part of the discussion leading up to that deprecation.

Maybe right around October 2015, when the GPIO character device ABI started as a response to user requests for a more rational alternative to the very broken `sysfs` approach - https://lore.kernel.org/all/1445502750-22672-1-git-send-email-linus.walleij@linaro.org/

In the relative vacuum that we left by ignoring Linux mainline. Bart then created `libgpiod`, a library to abstract away the complexities of interfacing with this new character device ABI - https://lore.kernel.org/all/1484747888-25092-1-git-send-email-bgolaszewski@baylibre.com/ - notably: `libgpiod` *is not the Linux Kernel GPIO character device ABI* and we should not conflate it as such in conversation.

It's worth searching lore.kernel.org since it includes well-reasoned discussion of all the rationale behind the changes, and how/why Linux explicitly separates concerns. For example, here's a question asked about PWM - https://lore.kernel.org/all/CAKdJ40QqZt3MbeLNZ1fuYRgaTqSJeDaDdHkQSx1-KWCW4BcJPg@mail.gmail.com/T/

It's the responsibility of a downstream library like WiringPi to:

1. Embrace the standards as they are presented to us
2. Extend them with common usage patterns, software PWM is the canonical example of this
3. Support end-users with examples and documentation

WiringPi *could* do this, but it requires someone with the time and inclination to do so. Since it's already a deprecated library dragged out on life support with a codebase I'm sure nobody involved really truly understands, I'm going to guess that someone wont be forthcoming.

### WringPi users: here's what you can do:

* If you want a fix, offer a bounty or submit a PR
* Otherwise cross your fingers and wait...
* or migrate to `lgpio` - https://github.com/joan2937/lg 
* or `libgpiod - https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git
* or write your own library and get all the kudos (and hassle) of being a maintainer!

**Comment by df8oe** [comment]
For me this GPIO business is the only thing - and it is absolutels mandatory to use GPIOs on computers like raspberry pi. They are often used for controlling purgoses / house automation and the would loose completely their sense if GPIOs are unusable. I would switch to lgpio or libgpiod but I miss examples how to use interrupts with these libraries. Maybe the deprecation of sysfs was announced - but I feel like I am in "Hitchhikers Guide to the Galaxy" where earth people missed the announcement of destroying the earth which can only be found lightyears away...

**Comment by Gadgetoid** [comment]
> I would switch to lgpio or libgpiod but I miss examples how to use interrupts with these libraries

It's right in the documentation- https://abyz.me.uk/lg/lgpio.html#lgGpioSetSamplesFunc

lgpio hurts my brain - it's sort-of close to libgpiod but has horrible mangled C-style names for everything - but there's a straight up canned example right there.

> Maybe the deprecation of sysfs was announced - but I feel like I am in "Hitchhikers Guide to the Galaxy" where earth people missed the announcement of destroying the earth which can only be found lightyears away...

I feel your pain here. I have DOZENS of libraries affected by changes with Pi 5 and Bookworm and it's consuming weeks of my time fixing everything, but if you're going to rely on a free library with effectively no maintainers then you're going to get effectively no support... such is the bittersweet nature of open source.

In an ideal world, people with a vested interest in maintaining WiringPi would have seen this change a mile off and fixed it before you even had to know, but where Gordon (the original author) had a financial incentive to keep WiringPi updated, it's now just a floundering liability for those of us who adopted it. No suitable maintainer has materialized in quite some time, I don't think it's any more likely to happen now.

That RPi don't have strong, well-documented, in-house solutions to GPIO on their platform is kinda absurd to me- `lgpio` is about as close as you're going to get.

**Comment by 6by9** [comment]
> I would switch to lgpio or libgpiod but I miss examples how to use interrupts with these libraries.

Callbacks, not interrupts. They are very different in terms of the context they are run in.

One of the libgpiod examples - https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/examples/watch_multiple_line_values.c
And if you're watching multiple GPIOs it is thread safe, unlike registering for multiple GPIOs with each call to `wiringPiISR` spawning a new "watching" thread.

**Comment by seamusdemora** [comment]
@6by9 : 
> sysfs for GPIO has always sucked with things like no concept of ownership, and having to have a file descriptors per gpio. Please accept that it is going the way of the dodo, or sign up to linux-gpio mailing list and express your displeasure there. It's a mainline decision, so complaining about it here or about the Pi kernel has very little effect.  

"always sucked"...  That's an interesting opinion, but imho, "works efficiently (uses few resources/quickly,etc)" presents a kind of rebuttal to that.

I tried the mailing list (briefly), but concluded that those people are focused on rather esoteric concerns. I felt it was a waste of my time IOW.

"complaining"??   I don't feel that my comments here amount to "complaining", but express a different viewpoint in terms of "where things should be headed". 

WRT libgpio dev in the kernel: I s'pose that Linus (with his now-immense wealth) is simply servicing his larger patrons in an economically rational way. But my reason for commenting here is something along this line: 

   *"I am a voice in the wilderness, and not too smart/knowledgeable wrt kernel dev matters.  The RPi community is larger, more influential and more knowledgeable than I, -and- they have a vested interest in seeing that the evolution of the gpio functions in the kernel move forward in a rational, efficient, effective way. If **you (RPi) guys** see the current path set by the kernel as a rational, efficient, effective one, then I'll guess that everything will work out fine eventually, and I can relax."* 

But that's not what I hear you saying - have I mis-understood something?  I can *"accept that [sysfs] is going the way of the dodo"*, but must its replacement sacrifice efficiency in the name of... what?  

Do you feel the direction that kernel developers are now taking will ultimately lead to a software edifice that works efficiently? 
 
> WiringPi is fixable to adapt to libgpio, but it needs someone (anyone - it's open source) to invest the time to do it. 

Well said, and true. I'm an over-70 electrical engineer who still enjoys tinkering. Software was **never** my thing, and I'm fairly certain that this is not how I should spend my time.

**Comment by seamusdemora** [comment]
@Gadgetoid : 

> That RPi don't have strong, well-documented, in-house solutions to GPIO on their platform is kinda absurd to me

That's a fair point I think.  So why do you think they (RPi guys) defer to the kernel devs for the gpio software edifice?

**Comment by Gadgetoid** [comment]
> That's a fair point I think. So why do you think they (RPi guys) defer to the kernel devs for the gpio software edifice?

Because it’s free and easy. 🤣

The Linus who wrote and proposed the GPIO character device ABI is not Linus Torvalds!

**Comment by seamusdemora** [comment]
> The Linus who wrote and proposed the GPIO character device ABI is not Linus Torvalds!  

No - I didn't presume that he was. I used his name only because he is the person who **presides over** (and presumably maintains some sort of control) all the kernel dev activities - which would include the gpio chardev ABI - which is a very minor component. Probably a bit like Mercedes Benz's CEO presides over what lug nuts are used in one of their models  :)

**Comment by seamusdemora** [comment]
@Gadgetoid 
> In the relative vacuum that we left by ignoring Linux mainline. Bart then created `libgpiod`, a library to abstract away the complexities of interfacing with this new character device ABI - https://lore.kernel.org/all/1484747888-25092-1-git-send-email-bgolaszewski@baylibre.com/ - notably: `libgpiod` _is not the Linux Kernel GPIO character device ABI_ and we should not conflate it as such in conversation.  

This is interesting!  I was not aware of this element of the evolution - that someone recognized how absurd the ABI (by itself) was for users, and developed a (yet another) layer of software to support ABI users. Yet I cannot help but wonder, that in forging this evolutionary path, if it suggests the process being followed is simply *feckless*?

I honestly don't mean to be critical - because I don't understand it well enough to be a critic - but here's how this sounds to me: 

*"We've just spent 8 years developing a software replacement for sysfs. This effort has produced two software components - the ABI and libgpiod - that may still be a bit clumsy and difficult to use, not "embraced" by anyone (AFAICT), and certainly not as efficient as sysfs."* 

Please correct my faulty perceptions.

**Comment by df8oe** [comment]
I am using RPI as many users do for controlling and house automation purposes.It is a very good and powerful alternative to Arduino and ESP32 devices. I am programming and developing hardware since I was able to walk and think (my skills are not high enough to transofm wiringpi to libgpiod). Interrupts are very often used in microcontrollers, and they do a very nice job (when you know what you are doing - as everywhere else). Wiringpi has offered a very simple programming structure to use pins "like an interrupt". Easy, fast, no CPU load that is noticeable. Im am a using vanilla kernel on Archlinuxarm so this impacted me very early. Most distributions use LTS kernel so the impact will be delayed there - but it *WILL COME*. Most standard users are using LTS kernel so I think big noise will pop up if this removement reaches LTS kernel. On Wiringpi using a pin as an interrupt only takes a few lines of code (max 10) and the code is very simple and absolutely easy to understand. I have dug the web for many hours but I was not able to find an example how to replace my code with libgpio code. And there is a rest of confuseness what is "future-proof". I do not know who is responsable for RPI specific software but I think this person or group should be informed what is impacting many devices in the near future. Not to forget all the other impacted devices (like orangepi and tens of same...)
